### ISSUE TITLE
Migrate remaining legacy tests to pytest

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/pycroft#580]
## description

The legacy `unittest` test base (`SQLAlchemyTestCase`) should be removed so we can utilize the power of the fixture dependency management and reuse of `pytest`.
It has been deprecated in 9ec91eee280d26261d3460597b3709948f99081e.

Finishes what has been started in #419 #533 #467

It would be interesting to compare the times of the test suite before and after the migration.

## Task list
<details><summary>command</summary>

```shell
pytest -m legacy --collect-only -Wignore tests | grep -Ei 'Package|Module|UnitTestCase' | sed -E 's/<[^ ]* (.*)>/- [ ] `\1`/'
```
</details>

- [x] `frontend` (#581)
- [x] `hades_logs`
- [x] `helpers`
- [x] `ldap_sync`              
  - [x] `test_ldap_sync.py`      
    - [x] `EmptyDatabaseTestCase`
    - [x] `OneUserFetchTestCase`
    - [x] `MultipleUsersFilterTestCase`   
    - [x] `LdapTestCase`
    - [x] `LdapOnceSyncedTestCase`
- [x] `lib`
  - [x] top-level test modules (#583)
  - [x] `lib.user` (#584)
- [x] `model`
- [x] `scripts`
  - [x] `test_schema.py`
    - [x] `TestSchemaStrategy`
    - [x] `TestUpgrade`
- [x] `table`

**Comment by lukasjuhrich** [comment]
Flask has some good pointers in its guide: https://flask.palletsprojects.com/en/2.2.x/testing/
